"""initial schema

Baseline revision: creates the schema that ``revenue_recovery.schema.METADATA``
describes, including the ``tasks`` queue table. Existing SQLite databases were
created by ``create_all`` with the same DDL, so stamping them instead of upgrading
(``alembic stamp ef01b3d6fa0c``) is the correct migration path for them.

Revision ID: ef01b3d6fa0c
Revises:
Create Date: 2026-08-28 00:13:35.016330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef01b3d6fa0c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_events',
    sa.Column('event_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('payment_id', sa.String(length=100), nullable=False),
    sa.Column('attempt_id', sa.String(length=100), nullable=False),
    sa.Column('customer_id', sa.String(length=100), nullable=False),
    sa.Column('subscription_id', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('gateway', sa.String(length=100), nullable=False),
    sa.Column('bank', sa.String(length=100), nullable=False),
    sa.Column('failure_code', sa.String(length=100), nullable=False),
    sa.Column('failure_category', sa.String(length=40), nullable=False),
    sa.Column('event_timestamp', sa.String(length=64), nullable=False),
    sa.Column('previous_success_count', sa.Integer(), nullable=False),
    sa.Column('previous_failure_count', sa.Integer(), nullable=False),
    sa.Column('customer_age_days', sa.Integer(), nullable=False),
    sa.Column('subscription_value', sa.Float(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_payment_events_amount_positive'),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('payment_id', 'attempt_id', name='uq_payment_events_payment_attempt')
    )
    with op.batch_alter_table('payment_events', schema=None) as batch_op:
        batch_op.create_index('ix_payment_events_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_payment_events_customer_id', ['customer_id'], unique=False)
        batch_op.create_index('ix_payment_events_failure_category', ['failure_category'], unique=False)

    op.create_table('audit_log',
    sa.Column('audit_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['payment_events.event_id'], ),
    sa.PrimaryKeyConstraint('audit_id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_log_event_id', ['event_id'], unique=False)

    op.create_table('decisions',
    sa.Column('decision_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('retry_delay_hours', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['payment_events.event_id'], ),
    sa.PrimaryKeyConstraint('decision_id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.create_index('ix_decisions_action', ['action'], unique=False)

    op.create_table('outcomes',
    sa.Column('outcome_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('recovered', sa.Integer(), nullable=True),
    sa.Column('recovered_amount', sa.Float(), nullable=False),
    sa.Column('final_state', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['payment_events.event_id'], ),
    sa.PrimaryKeyConstraint('outcome_id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.create_index('ix_outcomes_final_state', ['final_state'], unique=False)

    op.create_table('scores',
    sa.Column('score_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('recovery_probability', sa.Float(), nullable=False),
    sa.Column('churn_risk', sa.Float(), nullable=False),
    sa.Column('revenue_at_risk', sa.Float(), nullable=False),
    sa.Column('priority_score', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.CheckConstraint('churn_risk >= 0 AND churn_risk <= 1', name='ck_scores_churn_range'),
    sa.CheckConstraint('priority_score >= 0', name='ck_scores_priority_non_negative'),
    sa.CheckConstraint('recovery_probability >= 0 AND recovery_probability <= 1', name='ck_scores_probability_range'),
    sa.CheckConstraint('revenue_at_risk >= 0', name='ck_scores_revenue_non_negative'),
    sa.ForeignKeyConstraint(['event_id'], ['payment_events.event_id'], ),
    sa.PrimaryKeyConstraint('score_id'),
    sa.UniqueConstraint('event_id')
    )
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.create_index('ix_scores_priority_score', ['priority_score'], unique=False)

    op.create_table('tasks',
    sa.Column('task_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('run_at', sa.String(length=64), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('locked_by', sa.String(length=80), nullable=True),
    sa.Column('locked_at', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.String(length=64), nullable=False),
    sa.Column('updated_at', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['payment_events.event_id'], ),
    sa.PrimaryKeyConstraint('task_id'),
    sa.UniqueConstraint('event_id', 'task_type', name='uq_tasks_event_type')
    )
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index('ix_tasks_status_run_at', ['status', 'run_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index('ix_tasks_status_run_at')

    op.drop_table('tasks')
    with op.batch_alter_table('scores', schema=None) as batch_op:
        batch_op.drop_index('ix_scores_priority_score')

    op.drop_table('scores')
    with op.batch_alter_table('outcomes', schema=None) as batch_op:
        batch_op.drop_index('ix_outcomes_final_state')

    op.drop_table('outcomes')
    with op.batch_alter_table('decisions', schema=None) as batch_op:
        batch_op.drop_index('ix_decisions_action')

    op.drop_table('decisions')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_event_id')
        batch_op.drop_index('ix_audit_log_created_at')

    op.drop_table('audit_log')
    with op.batch_alter_table('payment_events', schema=None) as batch_op:
        batch_op.drop_index('ix_payment_events_failure_category')
        batch_op.drop_index('ix_payment_events_customer_id')
        batch_op.drop_index('ix_payment_events_created_at')

    op.drop_table('payment_events')
    # ### end Alembic commands ###
